#!/bin/sh -e
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x Installing homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "  + Homebrew found."
fi

brew install grc coreutils
brew install zsh
echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
brew install diff-so-fancy
brew install elasticsearch
brew install kibana
brew install logstash
brew install gcc
brew install git
brew install hub
brew install mongodb
brew install node
brew install yarn
brew install python
brew install the_silver_searcher
brew install wrk
brew install rabbitmq
brew install mysql
brew install rmtrash
brew install sqlite
brew install ipython
brew install postgresql
