#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
. init/homebrew

# Install GUI related cask using brew and cask itself 
. init/cask_installs

ln -sf ~/mygit/dotfiles/init/.myzshrc.sh ~/.myzshrc
ln -sf ~/mygit/dotfiles/git/.gitconfig ~/.gitconfig
