#!/bin/sh -e
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "  + Homebrew found."
fi

brew install zsh
echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
brew install diff-so-fancy
brew install gcc
brew install git
brew install the_silver_searcher
brew install wrk
brew install rmtrash
brew install pkg-config
brew install jq
brew install fd
brew install tldr
brew install prettyping
brew install grc
brew install coreutils
brew install autojump
brew install zsh-autosuggestions
brew install asdf
