alias reload!='. ~/.zshrc'
alias mou='/Applications/Mou.app/Contents/MacOS/Mou'
alias bi='bundle install '
alias ginit='git init && git add . && git commit -am "Initial commit"'
alias set_heroku='~/dev/repos/shorts/set_heroku_env.sh'
alias history='history -100'
alias clean_routes="rake routes | sed -e '1d' -e 's,^[^/]*,,g' | awk '{print $1}' | sort | uniq"
alias m="ssh admin@monitorin"
alias jenk="java -jar /usr/local/opt/jenkins/libexec/jenkins.war"
alias gr="git fetch origin ; git rebase -p"
alias start_all="memcached & ; redis-up ; mysup ; mongod &; rabbitmq-server &"
alias encrypt="openssl des3 -in ~/important.txt -out ~/encrypted.txt"
alias decrypt="openssl des3 -d -in ~/encrypted.txt"
alias show_locks="cd ~/ && find . -type f -flags +uchg && cd - "
alias static_server="ruby -run -e httpd . --port 8080"
alias brack="/Applications/Brackets.app/Contents/MacOS/Brackets"
alias tunnel_moo="ssh -L 1234:moo:3000 admin@monitorin.fiverr.com"
alias tunnel_rabbit="ssh -L 1234:10.179.225.44:15672 admin@monitorin.fiverr.com"
