alias reload!='. ~/.zshrc'
alias ginit='git init && git add . && git commit -am "Initial commit"'
alias ll='ls -lrtah'
alias gr='git pull -r'
alias pullall='for i in */.git; do ( echo $i; cd $i/..; git pull; ); done'
alias history='history -100'
